# Generated by Django 4.1.7 on 2023-03-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra',
            options={'ordering': ('-price', 'description'), 'verbose_name': 'extra', 'verbose_name_plural': 'extras'},
        ),
    ]
