# Generated by Django 4.1.7 on 2023-04-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_extracartitem_extra_and_more'),
        ('cinema', '0003_alter_extra_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
