# Generated by Django 4.1.7 on 2023-04-13 16:11

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_delete_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='date',
            field=models.DateField(validators=[cinema.models.Screening.check_date]),
        ),
    ]
