# Generated by Django 4.1.7 on 2023-04-12 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='extra')),
            ],
            options={
                'verbose_name': 'extra',
                'verbose_name_plural': 'extras',
                'ordering': ('-price', 'description'),
            },
        ),
    ]
