# Generated by Django 4.1.7 on 2023-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_extra_options'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecartitem',
            name='numSeats',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='moviecartitem',
            name='seats',
            field=models.ManyToManyField(blank=True, to='cinema.seat'),
        ),
        migrations.AlterModelTable(
            name='extracartitem',
            table='ExtraCartItem',
        ),
        migrations.AlterModelTable(
            name='moviecartitem',
            table='MovieCartItem',
        ),
    ]
