# Generated by Django 4.1.7 on 2023-04-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_moviecartitem_numseats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecartitem',
            name='numSeats',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
