# Generated by Django 4.1.7 on 2023-04-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('cart', '0004_alter_moviecartitem_numseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracartitem',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.extra'),
        ),
        migrations.AlterField(
            model_name='moviecartitem',
            name='numSeats',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
